# file created : 2018.10.28
# file updated : 2018.10.29
# 
# Version 1.0.0 (2018-08-08)
# Base.MainInclude.include( "ProjectEuler/Problem0002/0002_02.jl" )
# 

# Project Euler
# https://projecteuler.net/problem=2
# Problem 0002 [Even Fibonacci numbers]
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

function FibonacciNum( term::Core.Integer )

	if Base.isequal( term , Base.one( term ) )
		return Base.one( term )
	elseif Base.isequal( term , Base.one( term )*2 )
		return Base.one( term )*2
	else

		# STEP.01
		# make buffer
		buff = Base.Vector{ Core.typeof( term ) }( Core.undef, term )

		# STEP.02
		# store initial condition
		buff[1] = FibonacciNum( Base.one( term )   )
		buff[2] = FibonacciNum( Base.one( term )*2 )

		# STEP.03
		# calculate the target term
		for itr ∈ 3:term
			buff[itr] = Base.Checked.checked_add( buff[itr-1] , buff[itr-2] )
		end

		# STEP.END
		return buff[term]

	end
end

function test( num_terms::Core.Integer )

	for itr ∈ Base.one( num_terms ) : num_terms
		Base.Printf.@printf( Base.stdout , "%4d %110d\n" , itr, FibonacciNum( Base.GMP.BigInt( itr ) ) )
	end

	return Core.nothing

end

# Base.@timev test( 20 )
# 0.053040 seconds (83.98 k allocations: 4.345 MiB)
# elapsed time (ns): 53040215
# bytes allocated:   4556158
# pool allocs:       83974
# non-pool GC allocs:9

# Base.@timev test( 30 )
# 0.072979 seconds (84.41 k allocations: 4.358 MiB)
# elapsed time (ns): 72978838
# bytes allocated:   4569630
# pool allocs:       84400
# non-pool GC allocs:9

# Base.@timev test( 40 )
# 0.087400 seconds (84.79 k allocations: 4.370 MiB)
# elapsed time (ns): 87399548
# bytes allocated:   4582174
# pool allocs:       84780
# non-pool GC allocs:9

Base.@timev test( 500 )
# 0.102984 seconds (85.13 k allocations: 4.382 MiB)
# elapsed time (ns): 102984007
# bytes allocated:   4594766
# pool allocs:       85119
# non-pool GC allocs:9